// https://docs.cypress.io/api/introduction/api.html

describe('Generated Code', () => {
    it('Visits the generated code', () => {
      cy.visit('localhost:8080/editor')
      cy.wait(2000)
    })
    it('Root', () => {
      cy.get('.pathElement').contains('restapi.yml')
      cy.get('p').contains('ApplicationDbContext.cs').click()
      cy.get('.pathElement').contains('ApplicationDbContext.cs')
      cy.get('p').contains('Startup.cs').click()
      cy.get('.pathElement').contains('Startup.cs')
    })
    it('ClientApp', () => {
      cy.get('p').contains('ClientApp').click()
      cy.get('p').contains('src').click()
      cy.get('p').contains('App.vue').click()
      cy.get('.pathElement').contains('App.vue')
      cy.get('p').contains('api').click()
      cy.get('p').contains('index.js').click()
      cy.get('.pathElement').contains('index.js')
      cy.get('p').contains('api').click()
      cy.get('p').contains('components').click()
      cy.get('p').contains('UserView.vue').click()
      cy.get('.pathElement').contains('UserView.vue')
      cy.get('p').contains('components').click()
      cy.get('p').contains('router').click()
      cy.get('p').contains('index.js').click()
      cy.get('.pathElement').contains('index.js')
      cy.get('p').contains('router').click()
      cy.get('p').contains('store').click()
      cy.get('p').contains('index.js').click()
      cy.get('.pathElement').contains('index.js')
      cy.get('p').contains('store').click()
      cy.get('p').contains('views').click()
      cy.get('p').contains('UserList.vue').click()
      cy.get('.pathElement').contains('UserList.vue')
      cy.get('p').contains('store').click()
      cy.get('p').contains('ClientApp').click()
    })
    it('Controllers', () => {
      cy.get('p').contains('Controllers').click()
      cy.get('p').contains('UsersController.cs').click()
      cy.get('.pathElement').contains('UsersController.cs')
      cy.get('p').contains('Entities').click()
      cy.get('p').contains('User.cs').click()
      cy.get('.pathElement').contains('User.cs')
      cy.get('p').contains('Entities').click()
      cy.get('p').contains('Services').click()
      cy.get('p').contains('UsersService.cs').click()
      cy.get('.pathElement').contains('UsersService.cs')
      cy.get('p').contains('Interfaces').click()
      cy.get('p').contains('IUsersService.cs').click()
      cy.get('.pathElement').contains('IUsersService.cs')
      cy.get('p').contains('Services').click()
      cy.get('p').contains('Controllers').click()
    })
  })
  